### ISSUE TITLE
Concerns About Security/Scope

### ISSUE THREAD

**Issue by nonissue** [JoeKuhns/PiedPiPer.safariextension#1]
A quick skim through the code for this extension shows that the script is injected on every page the user navigates to (both insecure and secure). This behaviour doesn't seem ideal. From a security standpoint, having a script injected in to every page viewed is definitely unwanted (I'm not saying the script is doing anything malicious, but it's possible it could be modified to do something malicious or used as a vector for some other kind of attack). 

A more minor concern is the performance hit (though slight) created by injecting a script that ultimately will only be necessary on a few sites.

A possibly better (though not as nifty/seamless) implementation would be to add a button to the safari toolbar that a user can click on to either (a) invoke the PiP functionality immediately if an applicable source is found in the currently loaded page (b) enable the current functionality (adding the custom button to the video player controls) so the user can then use that button going forward.

I have not developed a Safari extension before and so my experience is limited. Let me know if this does/doesn't make sense. There also may be some security details implemented I am missing.

**Comment by JoeKuhns** [comment]
It makes perfect sense.  This is my first safari extension.  There is a part I can add, where the script will only be injected into applicable domains.  I will add that later today and push a new version.

**Comment by JoeKuhns** [comment]
Just fixed.  New Version is up.
