### ISSUE TITLE
Plex support not working

### ISSUE THREAD

**Issue by ghost** [JoeKuhns/PiedPiPer.safariextension#12]
There is no button or right-click option in my Plex player.

I think this is due to
> Also fixed it so the plugin only fires on appropriate domains (netflix, youtube, dailymotion, plex).

since Plex videos don't actually play on `http://plex.tv`. They play on a local server, accessed through an IP address in the address bar.

**Comment by JoeKuhns** [comment]
You can also access your Plex through Plex.tv.  If you setup your Plex server with remote access enabled.  you can then access it through Plex.tv.  (It's still free no worries).  If I open the plug-in to fire on any page you go to, it is just a wast of resources and battery and everything else.  So for the moment, I don't think there is anything I can do.  If you want help on setting up Plex, let me know.

**Comment by ghost** [comment]
Okay, got it. Didn't see a way to access the server from Plex.tv initially. Thanks.
