### ISSUE TITLE
Settings for website control

### ISSUE THREAD

**Issue by thislooksfun** [JoeKuhns/PiedPiPer.safariextension#15]
Is it / would it be possible to enable/disable specific websites?
Namely, I want this for Netflix and not for YouTube, but I can't find a way to disable it just on one domain.

Thanks,
-tlf

**Comment by JoeKuhns** [comment]
Maybe, but currently I have no method setup to change settings.  The question I have is why do you want to disable it on youtube?

**Comment by thislooksfun** [comment]
Three reasons:

1. YouTube already has the double-right-click menu, so it's not strictly necessary.
2. As mentioned in #9, it doesn't fully work in fullscreen
3. And finally, the main reason: it doesn't work on embedded videos. The reason this is so annoying is that it shifts the fullscreen button over, and thus there can be no muscle memory since I need to look at the video before clicking, which slows me down.

The easy fixes for #3 are let me turn it off on YT, or add the button to the left of the stack, like you do on Netflix, so it doesn't interfere with the positions of the other buttons.

**Comment by JoeKuhns** [comment]
Fully valid.  I would rather solve the issues you have than allow options to disable.  but I will see what I can do for either.  I am hoping to put some significant time into this shortly.  I just finished a large deadline for work so time should be available again.

**Comment by JoeKuhns** [comment]
~~Can you give me an example of a youtube embedded it doesn't work on.  I just tried a bunch at it seems to work fine.   I would like to see whats going on and solve this.~~

Strike that.  If I dump my cache and play an embedded, no pip menu.  if I go to youtube.com and play a video, pip works.  then if I go back to a site with embedded it is there again.  This has to do with the domain filtering for the plugin.  I'll figure it out.  If I solve these will that work for you?  I'd rather not move the button as I have been getting a few hundred downloads a week and moving the icon at this point. may frustrate other users.

**Comment by thislooksfun** [comment]
As long as it consistently appears on all youtube players regardless of host site, the position doesn't matter. I offered that as a suggestion in case that level of filtering wasn't practical/possible.

**Comment by JoeKuhns** [comment]
Gonna close this.  as the new version I believe addresses all your issues, let me know if I missed something.  Granted the icon size is still miffed in fullscreen on youtube.  I'll fix that in the next day or two.
