### ISSUE TITLE
Support for TabloTV WebPlayer

### ISSUE THREAD

**Issue by arejay73** [JoeKuhns/PiedPiPer.safariextension#16]
Could you add support for the TabloTV Web player.  https://www.tablotv.com/tablo-products/#tablo-apps

**Comment by JoeKuhns** [comment]
I don't have a Tablo, so unless the good folks at table send me one... 

Without seeing and playing with the interface, I don't even know if it is possible (It could be flash).  So for now I am going to close this one.  Though I must say, it does look really tempting, how do you like it?

**Comment by arejay73** [comment]
I enjoy the tabloTV.  I have the 4 turner model and I could use a couple of more turners 'cause between the wife and kids during primetime can sometimes be an issue.  But It has worked great.  I would recommend as a solution in a cord cutting household.

From what I understand it is just a straight HTLM5 web client.  In fact, because I have use some scripts to pull off recordings to add shows to my plex server, I have seen URLs that I can plugin to my web browser and stream recordings.

**Comment by JoeKuhns** [comment]
try putting this command in the console.

`document.querySelector("video").webkitSetPresentationMode("picture-in-picture")`

If it is just straight html5 video that should jump it into PIP mode.  If that works we might be able to figure something out.  If you need help on where to put that command in, let me know.

**Comment by arejay73** [comment]
Yes.  I think I need help with that.  I opened the developer tool menu and tried adding your code to the console, but I got an error.

undefined.

I can send you the content of the HTML file is that would help.  It is a lot paste tho, about 96 lines.

**Comment by JoeKuhns** [comment]
Since we are the only ones in this issue... paste it in, why not.

**Comment by JoeKuhns** [comment]
undefined means it couldn't find the video, but that could be the result of many things.

**Comment by arejay73** [comment]
Wouldn't let paste the code so I uploaded a txt file.
[TabloPlayer.txt](https://github.com/JoeKuhns/PiedPiPer.safariextension/files/822045/TabloPlayer.txt)

**Comment by JoeKuhns** [comment]
Do you want to just go to my bio(on GitHub) and email me the code/file???  Wait, realized you can't see me email.  its my name at my name .com  i.e.  john@johndoe.com

**Comment by JoeKuhns** [comment]
Yeah, there isn't really anything there.  I would really need to see it in order to add it.  And unfortunately it doesn't look like I can even remotely access someone else's.

We can do one last try though.  right click on the webpage with a video playing.  when you see the html code.  you need to right clock on the second line.. It starts `<html`  then select copy html or copy outer html, depending on your browser.  Then try sending that to me.

**Comment by arejay73** [comment]
I am using safari.  Was the file empty?

**Comment by JoeKuhns** [comment]
No, the files wasn't empty, but it didn't have the functioning parts (video stuff) of the web app.  If you wan't to try my  last thought above, I can give it another go.

**Comment by arejay73** [comment]
Ok.  Sending over new files to review.  Look at the original file for the lines:
<script src="head.js"></script>
	<script src="/e3d7353cd63a6b3f82fb82e5282dab6d61d6c3ab.js"></script>
I am sending those as well.
[his-0.6.13.min.txt](https://github.com/JoeKuhns/PiedPiPer.safariextension/files/822555/his-0.6.13.min.txt)
[head.txt](https://github.com/JoeKuhns/PiedPiPer.safariextension/files/822554/head.txt)
[e3d7353cd63a6b3f82fb82e5282dab6d61d6c3ab.txt](https://github.com/JoeKuhns/PiedPiPer.safariextension/files/822556/e3d7353cd63a6b3f82fb82e5282dab6d61d6c3ab.txt)
![screen shot 2017-03-06 at 4 12 08 pm](https://cloud.githubusercontent.com/assets/870615/23630353/d1e79150-0288-11e7-8524-d0cc9d418381.png)

**Comment by JoeKuhns** [comment]
So I just read through some of it.  it uses React, so it will be a dog to get this working.  It took me about 10 hours to get Amazon going, and amazon is react, and it still isn't stable.  So lets do this.  Keep an eye on PiedPiper and if you see me do an update with the new Netflix and NBC, remind me of this.  if I get those going, that means I have figured out an easier way to defeat react.  Sorry I can't be more help on this one.  I hate to refer you to another plugin, but you can try Pipifier on the App Store.  He deals with the whole thing differently by adding a button to the toolbar.  It's a bit more manual in that you have to click the button and then click the video, but it may work for you.  I am more of a purist and prefer to add native looking pip buttons to systems.

**Comment by arejay73** [comment]
OK.  Thanks for your efforts.
