### ISSUE TITLE
Not working on macOS 10.12.4 Safari 10.1

### ISSUE THREAD

**Issue by davidnoelopez** [JoeKuhns/PiedPiPer.safariextension#18]
I think the last OS update broke the extension, I used it for a while before updating and now it's not working. Any work around?

**Comment by JoeKuhns** [comment]
Its still works on my test machines.  Are you sure it is still installed?  sometimes updates can delete the extension.

**Comment by davidnoelopez** [comment]
It was installed after the update and I tried reinstalling it, still didn't work.

**Comment by davidnoelopez** [comment]
nvm, I just reinstalled it again and it worked. Thanks! Sorry to bother you.
