### ISSUE TITLE
Not working with Plex?

### ISSUE THREAD

**Issue by AlecRobertson** [JoeKuhns/PiedPiPer.safariextension#21]
The button is not showing on the Plex player anymore.

**Comment by JoeKuhns** [comment]
It works on mine.  Did you do any updates recently?  Is the plugin still showing in safari?  How are you accessing Plex?  through Plex.tv or through your IP address?

**Comment by AlecRobertson** [comment]
My apologies, I was using it on a personal IP. Working fine on Plex.tv.

**Comment by JoeKuhns** [comment]
Unfortunately to help it be more stable and also not waste resources scanning every page that is visited, I had to limit the plugin to only scan certain domains.
