### ISSUE TITLE
Netflix Subtitles

### ISSUE THREAD

**Issue by Giuseppe5** [JoeKuhns/PiedPiPer.safariextension#3]
The subtitles on Netflix remain on the main page, do not show up in the PiP window
<img width="860" alt="screen shot 2016-10-15 at 12 37 23" src="https://cloud.githubusercontent.com/assets/18719316/19409455/2a65d136-92d4-11e6-90b5-5bea866cc1a0.png">

Edit: Looks like the same thing happens with youtube subtitles

**Comment by JoeKuhns** [comment]
I hadn't even thought about subtitles.  I'll take a look, I know subtitles work for iTunes with PiP so it is possible.  Unfortunately I have no idea how Netflix and youtube are packaging subtitles.  If they aren't part of the h264 stream it may not be possible.  I'll let you know.

**Comment by JoeKuhns** [comment]
So youtube and Netflix both render subtitles as html elements on top of the video.  This will be a tough one.  But I'll give it a shot.  If anyone else out there has any ideas how to get an xml converted to a vtt on the fly, any help would be appreciated.

**Comment by JoeKuhns** [comment]
I'm closing this issue as reencoding closed captions on the fly into the video stream is at the moment, near impossible (at least with my skills).  The new version does fix a number of bugs, so it is worth getting.
