### ISSUE TITLE
Extension DIsappears

### ISSUE THREAD

**Issue by JoeKuhns** [JoeKuhns/PiedPiPer.safariextension#4]
Pied Píper disappears from safari after some restarts.  Looking into the cause.

**Comment by aguite** [comment]
I'd love to, but it seems the link is broken to download the install file?

**Comment by JoeKuhns** [comment]
Sorry about that, just fixed.  Github seems to cache heavily, so you may have to refresh a couple of times.  or on the main code listing, there is the file called...   "PiedPiPer.safariextz". you can just download that.
