### ISSUE TITLE
Add support for Amazon Video

### ISSUE THREAD

**Issue by elliotpeele** [JoeKuhns/PiedPiPer.safariextension#8]
It would be nice if this worked for Amazon video streaming.

**Comment by JoeKuhns** [comment]
Just wanted to let you know I am working on this, but it is a real battle.  Hopefully soon.

**Comment by JoeKuhns** [comment]
I just posted a new version with early support for amazon.  It is flakey though.  The icon is currently in the bottom center of the screen.  I'll get it more stable soon.
